### ISSUE TITLE
Strange behavior With `rev_read` when reading > 370 bytes

### ISSUE THREAD

**Issue by rkabrick** [tactcomplabs/rev#192] opened 2023-11-01 14:51 UTC
**Describe the bug**
If you pass the call to `rev_read` inside the `file-io` test:
- `uint64_t bytesRead = rev_read(fd, buffer, 370);` --> Test Passes 
- `uint64_t bytesRead = rev_read(fd, buffer, 371);` --> Rev SegFault at address `0x3f636343` 
- `uint64_t bytesRead = rev_read(fd, buffer, 372);` --> Rev SegFault at address `0x63636343` 
- `uint64_t bytesRead = rev_read(fd, buffer, 374);` --> Rev SegFault at address `0x636363636343` 

**To Reproduce**
All issues must be accompanied by: 
- The version of SST utilized (`sst --version`; `sst-config --CXX`; `sst-config --ELEMENT_CXXFLAGS`)
SST-Core Version (13.0.0)
clang++
 -std=c++17 -fPIC -DHAVE_CONFIG_H -I/opt/homebrew/Cellar/sst/13.0.0/include

- The source code branch being used:
`devel` 

- The last commit hash: 
`c4f21a7cb9066b9529bd63b345ffb316bf9eb54c` 
- The compiler utilized to build Rev

- The compiler utilized to build the test
`riscv64-unknown-elf-gcc` 

- The python or JSON simulation input
`rev-test.py` inside of the `file-io` syscall test 

- C/CXX test source (or mention which test in the current source tree failed)
`file-io.c` when setting bytes to read > 370

**Expected behavior**
Test should pass 

**Trace**

`rev_read(fd, buffer, 371)`:
RevCPU[cpu:DecodeInst:77000]: Core 0; Hart 0; Thread 1; PC:InstPayload = 0x136fe:0xfef43023
 | BaseAddr:  0x3ffffc00 | TopAddr: 0x40000000 | Size: 1024 Bytes
 | BaseAddr:  0x10000 | TopAddr: 0x14000 | Size: 16384 Bytes
 | BaseAddr:  0x14000 | TopAddr: 0x15000 | Size: 4096 Bytes
 | BaseAddr:  0x3feffc00 | TopAddr: 0x3ffffc00 | Size: 1048576 Bytes
FATAL: RevCPU[cpu:CalcPhysAddr:77000]: Segmentation Fault: Virtual address 0x3f636343 (PhysAddr = 0xffffffffffffffff) was not found in any mem segments

`rev_read(fd, buffer, 372)`:
RevCPU[cpu:DecodeInst:77000]: Core 0; Hart 0; Thread 1; PC:InstPayload = 0x136fe:0xfef43023
 | BaseAddr:  0x3ffffc00 | TopAddr: 0x40000000 | Size: 1024 Bytes
 | BaseAddr:  0x10000 | TopAddr: 0x14000 | Size: 16384 Bytes
 | BaseAddr:  0x14000 | TopAddr: 0x15000 | Size: 4096 Bytes
 | BaseAddr:  0x3feffc00 | TopAddr: 0x3ffffc00 | Size: 1048576 Bytes
FATAL: RevCPU[cpu:CalcPhysAddr:77000]: Segmentation Fault: Virtual address 0x63636343 (PhysAddr = 0xffffffffffffffff) was not found in any mem segments

`rev_read(fd, buffer, 374)`:
RevCPU[cpu:DecodeInst:77000]: Core 0; Hart 0; Thread 1; PC:InstPayload = 0x136fe:0xfef43023
 | BaseAddr:  0x3ffffc00 | TopAddr: 0x40000000 | Size: 1024 Bytes
 | BaseAddr:  0x10000 | TopAddr: 0x14000 | Size: 16384 Bytes
 | BaseAddr:  0x14000 | TopAddr: 0x15000 | Size: 4096 Bytes
 | BaseAddr:  0x3feffc00 | TopAddr: 0x3ffffc00 | Size: 1048576 Bytes
FATAL: RevCPU[cpu:CalcPhysAddr:77000]: Segmentation Fault: Virtual address 0x636363636343 (PhysAddr = 0xffffffffffffffff) was not found in any mem segments

Notice the difference between the virtual addresses between runs.

**Additional context**
My initial thought is we are running out of stack space but we have a full megabyte... Additionally I have no idea why the address of the segfault changes to a 48-bit address from a 32-bit one based on reading 372 -> 374 bytes. Also it does not matter if the file being read from is actually > 370 bytes or not. Same behavior.

**Comment by ukasz** [comment] 2023-11-03 15:05
I tried this out of curiosity and I was not able to reproduce it on c4f21a7cb9. Did you modify anything else besides rev_read call, an input file maybe?

**Comment by leekillough** [comment] 2023-11-03 18:05
@rkabrick is on vacation for a week; I'll see if I can reproduce it.

**Comment by rkabrick** [comment] 2023-11-10 19:05
> Did you modify anything else besides rev_read call, an input file maybe?

I tried it with *just* modifying the `rev_read` call and then also modifying the `test.txt` file to be over 370 characters long. Both had the same outcome. 

I wonder if it's an issue exclusive to `unknown_elf`. I'll try to test with your compiler @ukasz

**Comment by rkabrick** [comment] 2023-11-10 22:34
I believe this is yet another issue stemming from compressed instructions

**Comment by ajmandadi** [comment] 2023-11-20 17:42
right, just to confirm compressed instructions disabled works!

**Comment by rkabrick** [comment] 2023-11-22 19:36
I hate compressed instructions

**Comment by leekillough** [comment] 2023-11-22 22:10
> I hate compressed instructions

I he cd is to

**Comment by donofrio** [comment] 2023-12-04 21:20
Just tested on latest devel - works with bytesRead > 370 (tested up to 400). Closing

**Closed by donofrio** 2023-12-04 21:20 UTC
